controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

presentation_controllers:
    resource:
        path: ../src/Presentation/Controller/
        namespace: App\Presentation\Controller
    type: attribute
